services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./schemas/iam_auth_schema.sql:/docker-entrypoint-initdb.d/iam_auth_schema.sql
      # - ./schemas/user_schema.sql:/docker-entrypoint-initdb.d/user_schema.sql
      # - ./schemas/category_schema.sql:/docker-entrypoint-initdb.d/category_schema.sql
      # - ./schemas/user_category_schema.sql:/docker-entrypoint-initdb.d/user_category_schema.sql
      # - ./schemas/podcast_schema.sql:/docker-entrypoint-initdb.d/podcast_schema.sql
      # - ./schemas/user_favorite_schema.sql:/docker-entrypoint-initdb.d/user_favorite_schema.sql
      # - ./schemas/user_podcast_schema.sql:/docker-entrypoint-initdb.d/user_podcast_schema.sql

volumes:
  postgres_data: